// Named imports only (never `import * as Icons`) so bundlers can tree-shake
// lucide-react down to just the glyphs this site actually uses, instead of
// pulling in the entire icon set.
import {
  Code2,
  FileCode2,
  Gem,
  Braces,
  FileCode,
  Palette,
  LayoutGrid,
  MonitorSmartphone,
  Atom,
  Network,
  Search,
  GitBranch,
  Sparkles,
  BrainCircuit,
  ChartSpline,
  Smartphone,
  AppWindow,
  ChartColumnBig,
  Table,
  Database,
  LayoutTemplate,
  Infinity as InfinityIcon,
  Blocks,
  Terminal,
  MessageCircle,
  Users,
  Puzzle,
  Repeat,
  Clock,
  Lightbulb,
  Flag,
  GraduationCap,
} from "lucide-react";
import { GithubIcon } from "../components/icons";

export const iconRegistry = {
  Code2,
  FileCode2,
  Gem,
  Braces,
  FileCode,
  Palette,
  LayoutGrid,
  MonitorSmartphone,
  Atom,
  Network,
  Search,
  GitBranch,
  Sparkles,
  BrainCircuit,
  ChartSpline,
  Smartphone,
  AppWindow,
  ChartColumnBig,
  Table,
  Database,
  LayoutTemplate,
  Infinity: InfinityIcon,
  Blocks,
  Terminal,
  MessageCircle,
  Users,
  Puzzle,
  Repeat,
  Clock,
  Lightbulb,
  Flag,
  GraduationCap,
  "brand:github": GithubIcon,
};

export function resolveIcon(name) {
  return iconRegistry[name] || Sparkles;
}
